[package]
name = "synacor"
version = "0.1.0"
authors = ["Matt Porter <matt.porter@cityfibre.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
log = "*"
